services:
  - type: web
    name: hermit-md
    repo: https://github.com/A-d-i-t-h-y-a-n/hermit-bot.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: RANDER_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: rnd_NSeNQugmsksjakXIsy3yIOHnK8y7
        required: true
      - key: SESSION_ID
        sync : HP_2024_DEC_20_APSWUR
        required: true
      - key: DATABASE_URL
        sync: false
        required: true
      - key: PREFIX
        sync: !
      - key: SUDO
        sync: false
      - key: MODE
        value: "private"
      - key: LOG_MSG
        value: "false"
      - key: AUTO_STATUS_VIEW
        value: "false"
      - key: READ_MSG
        value: "false"
      - key: ALWAYS_ONLINE
        value: "true"
      - key: START_MSG
        value: "true"
      - key: PORT
        value: "3000"
